# General
network_file: './envs/toy_segregated/network.gml'
population_file: './envs/toy_segregated/population.csv'
facilities_file: './envs/toy_segregated/facilities.csv'
# Applicable values: ['nearest_k', 'toy_model', 'distance_popularity', 'distance_composition']
preferences_model: 'toy_model'
# Needed if preferences_model = 'nearest_k' OR 'toy_model'
# nearest_k: 2
# Applicable values: ['first_choice', 'random_serial_dictatorship']
allocation_model: 'random_serial_dictatorship'
# Applicable values: ['none', 'random', 'closeness', 'betweenness', 'degree', 'group_closeness', 'group_betweenness', 'group_degree']
intervention_model: 'closeness'
# Total number of rounds in the simulation. At each round a preference+allocation takes place and (possibly) an intervention.
simulation_rounds: 10
# Total number of simulation rounds in which interventions happen. Interventions will happen every $ simulation_rounds // intervention_rounds $ round.
# Note that on the first simulation round there are no interventions -- they always start at the second round.
intervention_rounds: 2
# Total number of interventions to do in a single intervention round.
intervention_budget: 1
# How many times to run the agent rounds (preference + allocation) on each simulation round.
# Evaluation metrics will be calculated based on the average over these rounds. This is done because there's randomness in the preference/allocation modules.
allocation_rounds: 30
# If true, the parameters of the preference model will get updated at every simulation round, when applicable.
# For example, it will update a facility popularity or the composition of each facility based on the previous round.
update_preference_params: False
