# General
network_file: './envs/toy_segregated/network.gml'
population_file: './envs/toy_segregated/population.csv'
facilities_file: './envs/toy_segregated/facilities.csv'
# Applicable values: ['nearest_k']
preferences_model: 'nearest_k'
# Needed if preferences_model = 'nearest_k'
nearest_k: 1
# Applicable values: ['identity']
allocation_model: 'identity'
