# General
network_file: './envs/toy_segregated/network.gml'
population_file: './envs/toy_segregated/population.csv'
facilities_file: './envs/toy_segregated/facilities.csv'
# Applicable values: ['nearest_k', 'toy_model']
preferences_model: 'toy_model'
# Needed if preferences_model = 'nearest_k' OR 'toy_model'
# nearest_k: 2
# Applicable values: ['first_choice', 'random_serial_dictatorship']
allocation_model: 'random_serial_dictatorship'
# Applicable values: ['random']
intervention_model: 'random'
simulation_rounds: 5
